In [1]:
#Q1.Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

#Ans. The data type of the NumPy array arr is int64.

import numpy as np

# Create a NumPy array 'arr' with integers from 0 to 5
arr = np.arange(6)

# Print the data type of the array
arr_dtype = arr.dtype
arr_dtype


dtype('int64')

In [2]:
# Q2. Given a NumPy array 'arr', check if its data type is float64.
# arr = np.array([1.5, 2.6, 3.7])

# Ans.
arr = np.array([1.5, 2.6, 3.7])


is_float64 = arr.dtype == np.float64
is_float64


True

In [3]:
# Q3.  Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
# Ans.

arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

# Display the array
arr


array([1.+2.j, 3.+4.j, 5.+6.j])

In [4]:
# Q4. Convert an existing NumPy array 'arr' of integers to float32 data type.
# Ans.

arr_int = np.array([1, 2, 3, 4, 5], dtype=np.int32)


arr_float32 = arr_int.astype(np.float32)


arr_float32, arr_float32.dtype


(array([1., 2., 3., 4., 5.], dtype=float32), dtype('float32'))

In [5]:
# Q5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

# Ans. To convert a NumPy array arr from float64 to float32 and reduce decimal precision, you can use the .astype() method:

arr = np.array([1.123456789, 2.987654321, 3.456789012], dtype=np.float64)


arr_float32 = arr.astype(np.float32)


print(arr_float32)


[1.1234568 2.9876542 3.456789 ]


In [6]:
# Q6.Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
# Ans.

def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    data_type = arr.dtype
    return shape, size, data_type

In [3]:
# Q7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

# Ans.
def array_dimension(arr):
    return arr.ndim

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_dimension(arr))  # Output: 2 (since it's a 2D array)



2


In [2]:
#Q8.Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

#Ans.You can design the item_size_info function using the .itemsize and .nbytes attributes of a NumPy array.
# The .itemsize gives the size (in bytes) of each element of the array, and .nbytes gives the total number of bytes consumed by the entire array.
# Here's how the function would look:

def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
item_size, total_size = item_size_info(arr)

print(f"Item size: {item_size} bytes")
print(f"Total size: {total_size} bytes")

Item size: 8 bytes
Total size: 48 bytes


In [9]:
#Q9.Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

#Ans.The strides attribute of a NumPy array gives you the number of bytes to step in each dimension when traversing the array.
#  Here's a function array_strides that takes a NumPy array as input and returns its strides:


def array_strides(arr):
    return arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
strides = array_strides(arr)

print(f"Strides: {strides}")


Strides: (24, 8)


In [4]:
# Q10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
# and strides of the array.

# Ans. To design the function shape_stride_relationship that returns both the shape and the strides of a NumPy array,
# you can use the .shape and .strides attributes of the array. Here's how you can implement the function:

def shape_stride_relationship(arr):
    shape = arr.shape  # Shape of the array
    strides = arr.strides  # Strides of the array
    return shape, strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
shape, strides = shape_stride_relationship(arr)

print(f"Shape: {shape}")
print(f"Strides: {strides}")


Shape: (2, 3)
Strides: (24, 8)


In [5]:
# Q11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
# zeros with `n` elements.

# Ans. You can create a function create_zeros_array that generates a NumPy array of zeros with n elements using np.zeros().
# Here's the function implementation:

def create_zeros_array(n):
    return np.zeros(n)

# Example usage
n = 5
zeros_array = create_zeros_array(n)
print(zeros_array)


[0. 0. 0. 0. 0.]


In [6]:
# Q12.Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
# NumPy array filled with ones of size `rows x cols`.

# Ans. You can create a function create_ones_matrix that takes rows and cols as inputs and generates a 2D NumPy array filled with ones using np.ones().
# Here's the function implementation:


def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

# Example usage
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
#Q13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
# creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
# `step`.

#Ans. You can create the function generate_range_array using np.arange(), which generates a NumPy array with values starting from start, ending at stop (exclusive), and incrementing by step.
# Here's how you can implement it:

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

# Example usage
start = 2
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print(range_array)


[2 4 6 8]


In [12]:
# Q14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
# arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
# (inclusive).

# Ans. You can use np.linspace() to generate an array with num equally spaced values between start and stop (inclusive).
# Here's the function generate_linear_space:


def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

# Example usage
start = 1.0
stop = 5.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)
print(linear_space_array)


[1. 2. 3. 4. 5.]


In [13]:
# Q15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
# identity matrix of size `n x n` using `numpy.eye`.

# Ans. You can use the np.eye() function to create an identity matrix. Here's how you can implement the create_identity_matrix function:


def create_identity_matrix(n):
    return np.eye(n)

# Example usage
n = 4
identity_matrix = create_identity_matrix(n)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
# Q16. Write a function that takes a Python list and converts it into a NumPy array.

# Ans. You can easily convert a Python list into a NumPy array using the np.array() function. Here's how you can implement the function:

def list_to_numpy_array(py_list):
    return np.array(py_list)

# Example usage
py_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(py_list)
print(numpy_array)


[1 2 3 4 5]


In [14]:
# Q17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
# same data.

# Ans. You can use the numpy.view() method to create a new array object that shares the same data as the original array but may have a different shape, data type, or other properties.
# Here's an example of how to use numpy.view():

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Use .view() to create a new array object with the same data
view_arr = arr.view()

# Modify an element in the view array to show that it affects the original array
view_arr[0] = 100

# Print the original and view arrays
print("Original array:", arr)
print("View array:", view_arr)


Original array: [100   2   3   4   5]
View array: [100   2   3   4   5]


In [18]:
# Q18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

# Ans. Here's a function that takes two NumPy arrays and concatenates them along a specified axis:

def concatenate_arrays(arr1, arr2, axis=0):
    """
    Concatenate two NumPy arrays along the specified axis.

    Parameters:
    arr1 (numpy.ndarray): First array to concatenate.
    arr2 (numpy.ndarray): Second array to concatenate.
    axis (int): Axis along which to concatenate. Default is 0.

    Returns:
    numpy.ndarray: Concatenated array.
    """
    return np.concatenate((arr1, arr2), axis=axis)




In [19]:
# Example(Q18)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = concatenate_arrays(arr1, arr2, axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
# Q19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
#  concatenate`.

# Ans. To concatenate two NumPy arrays horizontally using numpy.concatenate, they must have the same number of rows (i.e., the same first dimension). If the shapes are incompatible, you'll get an error.
# Here's an example:

# Create two NumPy arrays with different shapes
array1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
array2 = np.array([[7, 8], [9, 10]])       # Shape (2, 2)

# Concatenate horizontally (axis=1)
result = np.concatenate((array1, array2), axis=1)

print("Concatenated Array:")
print(result)


Concatenated Array:
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [21]:
# Q20. Write a function that vertically stacks multiple NumPy arrays given as a list.

# Ans. Here's a function that vertically stacks multiple NumPy arrays using numpy.vstack:

def vertical_stack(arrays):
    """
    Vertically stacks multiple NumPy arrays.

    Parameters:
    arrays (list of np.ndarray): A list of NumPy arrays to be stacked.

    Returns:
    np.ndarray: A single vertically stacked NumPy array.
    """
    return np.vstack(arrays)

# Example usage:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4, 5, 6]])
array3 = np.array([[7, 8, 9]])

result = vertical_stack([array1, array2, array3])
print(result)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
# Q21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
# with a given step size.

# Ans. Here's a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size:

def create_range_array(start, end, step):
    """
    Creates a NumPy array of integers within a specified range (inclusive) with a given step size.

    Parameters:
    start (int): The starting value of the range.
    end (int): The ending value (inclusive).
    step (int): The step size between consecutive values.

    Returns:
    np.ndarray: A NumPy array containing the sequence.
    """
    return np.arange(start, end + step, step)

# Example usage:
result = create_range_array(1, 10, 2)
print(result)


[ 1  3  5  7  9 11]


In [23]:
# Q22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
# (inclusive).

# Ans. Here's a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive):

def generate_linspace_array():
    """
    Generates a NumPy array of 10 equally spaced values between 0 and 1 (inclusive).

    Returns:
    np.ndarray: A NumPy array containing 10 equally spaced values.
    """
    return np.linspace(0, 1, 10)

# Example usage:
result = generate_linspace_array()
print(result)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [24]:
# Q23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
# 1000 (inclusive).

# Ans. Here's a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive):

def generate_logspace_array():
    """
    Generates a NumPy array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

    Returns:
    np.ndarray: A NumPy array containing 5 logarithmically spaced values.
    """
    return np.logspace(0, 3, 5)  # 10^0 to 10^3, with 5 values

# Example usage:
result = generate_logspace_array()
print(result)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [25]:
# Q24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
# are random integers between 1 and 100.

# Ans. Here's how you can create a Pandas DataFrame using a NumPy array with 5 rows and 3 columns, filled with random integers between 1 and 100:

import numpy as np
import pandas as pd

# Generate a 5x3 array of random integers between 1 and 100
data = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame
df = pd.DataFrame(data, columns=['A', 'B', 'C'])

# Display the DataFrame
print(df)


    A   B   C
0  21  70  11
1  85  33  53
2  30  73  57
3  46  10   3
4  69  93  80


In [26]:
# Q25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
# with zeros. Use NumPy operations within the Pandas DataFrame.

# Ans. Here's a function that replaces all negative values in a specific column of a Pandas DataFrame with zeros using NumPy operations:

def replace_negatives_with_zero(df, column_name):
    """
    Replaces all negative values in a specific column of a Pandas DataFrame with zeros.

    Parameters:
    df (pd.DataFrame): The input DataFrame.
    column_name (str): The name of the column to modify.

    Returns:
    pd.DataFrame: A new DataFrame with negative values replaced.
    """
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

# Example usage:
data = {'A': [10, -5, 20, -3, 15], 'B': [7, 8, -2, 4, -1]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Replace negatives in column 'A'
df = replace_negatives_with_zero(df, 'A')

print("\nModified DataFrame:")
print(df)


Original DataFrame:
    A  B
0  10  7
1  -5  8
2  20 -2
3  -3  4
4  15 -1

Modified DataFrame:
    A  B
0  10  7
1   0  8
2  20 -2
3   0  4
4  15 -1


In [27]:
# Q26. Access the 3rd element from the given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])

# Ans. You can access the 3rd element (index 2, since Python uses zero-based indexing) from the given NumPy array like this:

arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2)
third_element = arr[2]

print(third_element)


30


In [28]:
# Q27. Retrieve the element at index (1, 2) from the 2D NumPy array.
#  arr_2d = np.array([[1, 2, 3],
#                     [4, 5, 6],
#                     [7, 8, 9]])

# Ans. To retrieve the element at index (1,2) from the given 2D NumPy array, use the following code:

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Access the element at row index 1, column index 2
element = arr_2d[1, 2]

print(element)


6


In [29]:
# Q28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
# arr = np.array([3, 8, 2, 10, 5, 7])

# Ans.


arr = np.array([3, 8, 2, 10, 5, 7])

# Boolean indexing to extract elements greater than 5
elements_greater_than_5 = arr[arr > 5]

elements_greater_than_5


array([ 8, 10,  7])

In [30]:
# Q29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
#  arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#  Ans.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extract elements from index 2 to 5 (inclusive)
sliced_array = arr[2:6]  # Note: the end index is exclusive, so we use 6

sliced_array


array([3, 4, 5, 6])

In [31]:
# Q30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
#  arr_2d = np.array([[1, 2, 3],
#                     [4, 5, 6],
#                     [7, 8, 9]])

#  Ans.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slice the array to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[:2, 1:]

sub_array


array([[2, 3],
       [5, 6]])

In [32]:
# Q31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices
# provided in another array.

# Ans. Here's a NumPy function to extract elements in a specific order from a given 2D array based on indices provided in another array:

def extract_elements(arr, indices):
    """
    Extracts elements from a given 2D NumPy array based on provided indices.

    Parameters:
    arr (np.ndarray): The input 2D NumPy array.
    indices (list of tuples): A list of (row, col) index tuples specifying which elements to extract.

    Returns:
    np.ndarray: A 1D array of extracted elements.
    """
    row_indices, col_indices = zip(*indices)  # Unzip row and column indices
    return arr[np.array(row_indices), np.array(col_indices)]

# Example usage:
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

indices = [(0, 2), (2, 1), (1, 0)]  # Extract elements at (0,2), (2,1), and (1,0)

result = extract_elements(arr_2d, indices)
print(result)


[3 8 4]


In [33]:
# Q32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
# boolean indexing.

# Ans. Here's a NumPy function that filters elements greater than a given threshold using boolean indexing:

def filter_greater_than(arr, threshold):
    """
    Filters elements greater than a given threshold from a 1D NumPy array using boolean indexing.

    Parameters:
    arr (np.ndarray): The input 1D NumPy array.
    threshold (int or float): The threshold value.

    Returns:
    np.ndarray: A new array containing elements greater than the threshold.
    """
    return arr[arr > threshold]

# Example usage:
arr = np.array([10, 25, 3, 45, 7, 30])
threshold = 20

result = filter_greater_than(arr, threshold)
print(result)


[25 45 30]


In [34]:
#Q33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
# separate arrays for each dimension.

# Ans.

def extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3):
    """
    Extracts elements from a 3D NumPy array using indices provided in separate arrays.

    Args:
        arr_3d: The 3D NumPy array.
        indices_dim1: Array of indices for the first dimension.
        indices_dim2: Array of indices for the second dimension.
        indices_dim3: Array of indices for the third dimension.

    Returns:
        A 1D NumPy array containing the extracted elements.
    """

    # Validate the input indices
    if not (len(indices_dim1) == len(indices_dim2) == len(indices_dim3)):
        raise ValueError("Index arrays must have the same length.")

    # Perform the extraction using advanced indexing.
    extracted_elements = arr_3d[indices_dim1, indices_dim2, indices_dim3]
    return extracted_elements


In [35]:
#Q34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
# using boolean indexing.

# Ans.

def filter_by_two_conditions(arr, condition1, condition2):
    """
    Filters a NumPy array based on two conditions using boolean indexing.

    Args:
        arr: The input NumPy array.
        condition1: The first condition (a boolean array or a function).
        condition2: The second condition (a boolean array or a function).

    Returns:
        A new NumPy array containing elements that satisfy both conditions.
    """
    if callable(condition1):
        condition1 = condition1(arr)
    if callable(condition2):
        condition2 = condition2(arr)

    mask = condition1 & condition2  # Combine the conditions using the logical AND operator
    return arr[mask]

# Example usage
arr = np.array([1, 5, 10, 15, 20, 25, 30])

# Define two conditions
condition1 = arr > 10  # Elements greater than 10
condition2 = arr < 25  # Elements less than 25


filtered_array = filter_by_two_conditions(arr, condition1, condition2)
print(filtered_array)  # Output: [15 20]

# Example using functions as conditions
def is_even(x):
    return x % 2 == 0

def greater_than_5(x):
    return x > 5

filtered_array = filter_by_two_conditions(arr, is_even, greater_than_5)
filtered_array


[15 20]


array([10, 20, 30])

In [36]:
#Q35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
# in separate arrays.

# Ans.

def extract_elements_2d(arr, row_indices, col_indices):
    """
    Extracts elements from a 2D NumPy array using row and column indices.

    Args:
        arr: The 2D NumPy array.
        row_indices: A 1D NumPy array of row indices.
        col_indices: A 1D NumPy array of column indices.

    Returns:
        A 1D NumPy array containing the extracted elements.
    """
    # Validate input
    if not isinstance(arr, np.ndarray) or arr.ndim != 2:
        raise ValueError("Input 'arr' must be a 2D NumPy array.")

    if not (isinstance(row_indices, np.ndarray) and isinstance(col_indices, np.ndarray)):
      raise ValueError("Input 'row_indices' and 'col_indices' must be NumPy arrays.")

    if not (row_indices.ndim == 1 and col_indices.ndim == 1):
      raise ValueError("Input 'row_indices' and 'col_indices' must be 1D NumPy arrays.")

    if not len(row_indices) == len(col_indices):
      raise ValueError("Input 'row_indices' and 'col_indices' must have the same length.")

    # Extract elements using advanced indexing
    extracted_elements = arr[row_indices, col_indices]
    return extracted_elements

# Example Usage
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 0, 2])

extracted_values = extract_elements_2d(arr_2d, row_indices, col_indices)
extracted_values


array([2, 4, 9])

In [37]:
#Q36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

# Ans.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result_array = arr + 5
result_array


array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [38]:
#Q37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
# corresponding element in arr1 using NumPy broadcasting.

# Ans.
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

result_array = arr1 * arr2
result_array


ValueError: operands could not be broadcast together with shapes (1,3) (3,4) 

In [39]:
# Q38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
# NumPy broadcasting.

# Ans.
# Assuming arr1 and arr2 are already defined as in the problem description.
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

result_array = arr1 + arr2
result_array


ValueError: operands could not be broadcast together with shapes (1,4) (4,3) 

In [40]:
# Q39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
# broadcasting.

# Ans.
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])

result_array = arr1 + arr2
result_array


array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [42]:
# Q40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
# broadcasting. Handle the shape incompatibility.

# Ans.
def multiply_arrays(arr1, arr2):
    """
    Performs multiplication of two NumPy arrays using broadcasting, handling shape incompatibility.

    Args:
        arr1: The first NumPy array.
        arr2: The second NumPy array.

    Returns:
        The result of the multiplication, or None if the arrays cannot be multiplied due to shape incompatibility.
    """
    try:
      result = arr1 * arr2
      return result
    except ValueError as e:
      print(f"Error: {e}")
      return None


# Example usage
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])

result = multiply_arrays(arr1, arr2)

if result is not None:
  result


Error: operands could not be broadcast together with shapes (2,3) (2,2) 


In [43]:
# Q41. Calculate column-wise mean for the given array:
#  arr = np.array([[1, 2, 3], [4, 5, 6]])


# Ans.
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_means = np.mean(arr, axis=0)
column_means


array([2.5, 3.5, 4.5])

In [44]:
# Q42. Find maximum value in each row of the given array:
#  arr = np.array([[1, 2, 3], [4, 5, 6]])

# Ans.
arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max = np.max(arr, axis=1)
row_max


array([3, 6])

In [45]:
# Q43. For the given array, find indices of maximum value in each column.
#  arr = np.array([[1, 2, 3], [4, 5, 6]])

# Ans.
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_indices = np.argmax(arr, axis=0)
max_indices


array([1, 1, 1])

In [46]:
# Q44. For the given array, apply custom function to calculate moving sum along rows.
#  arr = np.array([[1, 2, 3], [4, 5, 6]])

# Ans.

def moving_sum(arr):
    """Calculates the moving sum along rows of a 2D NumPy array.

    Args:
    arr (np.ndarray): The input 2D array.

    Returns:
    np.ndarray: A new array with the moving sums.
    """

    # Check if the array is 2D
    if arr.ndim != 2:
        raise ValueError("Input array must be 2-dimensional.")

    rows, cols = arr.shape
    result = np.zeros_like(arr, dtype=int)  # Initialize the result array

    for i in range(rows):
        current_sum = 0
        for j in range(cols):
            current_sum += arr[i, j]
            result[i, j] = current_sum

    return result


# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
moving_sum_result = moving_sum(arr)
moving_sum_result


array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [47]:
# Q45. In the given array, check if all elements in each column are even.
#  arr = np.array([[2, 4, 6], [3, 5, 7]])

# Ans.
arr = np.array([[2, 4, 6], [3, 5, 7]])

def check_even_columns(array):
  """
  Checks if all elements in each column of a 2D NumPy array are even.

  Args:
    array: A 2D NumPy array.

  Returns:
    A boolean array indicating whether each column consists of only even numbers.
  """
  return np.all(array % 2 == 0, axis=0)

result = check_even_columns(arr)
result


array([False, False, False])

In [49]:
# Q46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
# reshaped matrix.
#  original_array = np.array([1, 2, 3, 4, 5, 6])

# Ans.

def reshape_array(arr, m, n):
    """
    Reshapes a NumPy array into a matrix of dimensions m rows and n columns.

    Args:
        arr (np.ndarray): The input NumPy array.
        m (int): The desired number of rows.
        n (int): The desired number of columns.

    Returns:
        np.ndarray: The reshaped matrix, or None if the reshape operation fails.
    """
    try:
        reshaped_arr = arr.reshape(m, n)
        return reshaped_arr
    except ValueError:
        print("Error: The array cannot be reshaped to the specified dimensions.")
        return None

# Example usage:
original_array = np.array([1, 2, 3, 4, 5, 6])
m = 2
n = 3

reshaped_matrix = reshape_array(original_array, m, n)

if reshaped_matrix is not None:
  reshaped_matrix


In [51]:
# Q47. Create a function that takes a matrix as input and returns the flattened array.
#  input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Ans.

def flatten_matrix(input_matrix):
    """
    Flattens a given matrix into a 1D array.

    Args:
        input_matrix (np.ndarray): The input matrix.

    Returns:
        np.ndarray: The flattened array.
    """
    return input_matrix.flatten()

# Example usage
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
flattened_array


array([1, 2, 3, 4, 5, 6])

In [52]:
# Q48. Write a function that concatenates two given arrays along a specified axis.
#  array1 = np.array([[1, 2], [3, 4]])
#  array2 = np.array([[5, 6], [7, 8]])

# Ans.

def concatenate_arrays(array1, array2, axis):
    """
    Concatenates two NumPy arrays along a specified axis.

    Args:
        array1: The first NumPy array.
        array2: The second NumPy array.
        axis: The axis along which to concatenate the arrays (0 for rows, 1 for columns).

    Returns:
        The concatenated NumPy array, or None if the arrays cannot be concatenated.
    """
    try:
        concatenated_array = np.concatenate((array1, array2), axis=axis)
        return concatenated_array
    except ValueError as e:
        print(f"Error: {e}")
        return None

# Example usage:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along rows (axis=0)
result_rows = concatenate_arrays(array1, array2, 0)
print("Concatenated along rows:")
if result_rows is not None:
    print(result_rows)

# Concatenate along columns (axis=1)
result_cols = concatenate_arrays(array1, array2, 1)
print("\nConcatenated along columns:")
if result_cols is not None:
  result_cols


Concatenated along rows:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along columns:


In [53]:
# Q49. Create a function that splits an array into multiple sub-arrays along a specified axis.
#  original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Ans.

def split_array(original_array, axis, indices_or_sections):
    """Splits a NumPy array into multiple sub-arrays along a specified axis.

    Args:
        original_array (np.ndarray): The input array to split.
        axis (int): The axis along which to split the array (0 for rows, 1 for columns).
        indices_or_sections (int or list): If an integer, it specifies the number of equal-sized sub-arrays.
                                           If a list, it specifies the indices at which to split the array.

    Returns:
        A list of NumPy sub-arrays, or None if the input is invalid or splitting fails.
    """
    try:
        if isinstance(indices_or_sections, int):
            # Split into equal-sized sub-arrays
            return np.split(original_array, indices_or_sections, axis=axis)
        elif isinstance(indices_or_sections, list):
            # Split at specific indices
            return np.split(original_array, indices_or_sections, axis=axis)
        else:
            print("Error: indices_or_sections must be an integer or a list.")
            return None
    except ValueError as e:
        print(f"Error: {e}")
        return None

# Example usage
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Split into 3 equal sub-arrays along axis 0 (rows):
sub_arrays = split_array(original_array, 0, 3)
if sub_arrays is not None:
    for i, sub_array in enumerate(sub_arrays):
        print(f"Sub-array {i+1}:\n{sub_array}")

# Split along axis 1 (columns) at indices 1 and 2
sub_arrays = split_array(original_array, 1, [1,2])
if sub_arrays is not None:
    for i, sub_array in enumerate(sub_arrays):
        print(f"Sub-array {i+1}:\n{sub_array}")


Sub-array 1:
[[1 2 3]]
Sub-array 2:
[[4 5 6]]
Sub-array 3:
[[7 8 9]]
Sub-array 1:
[[1]
 [4]
 [7]]
Sub-array 2:
[[2]
 [5]
 [8]]
Sub-array 3:
[[3]
 [6]
 [9]]


In [54]:
# Q50. Write a function that inserts and then deletes elements from a given array at specified indices.
#  original_array = np.array([1, 2, 3, 4, 5])
#  indices_to_insert = [2, 4]
#  values_to_insert = [10, 11]
#  indices_to_delete = [1, 3]

# Ans.

def modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    """Inserts and deletes elements from a NumPy array at specified indices.

    Args:
        original_array (np.ndarray): The input array.
        indices_to_insert (list): Indices where elements should be inserted.
        values_to_insert (list): Values to be inserted.
        indices_to_delete (list): Indices of elements to be deleted.

    Returns:
        np.ndarray: The modified array.
    """

    # Create a copy to avoid modifying the original array
    modified_array = np.copy(original_array)

    # Insert elements
    for i, index in enumerate(indices_to_insert):
        modified_array = np.insert(modified_array, index, values_to_insert[i])

    # Delete elements (adjust indices after insertions)
    adjusted_delete_indices = []
    for index in indices_to_delete:
        adjusted_index = index
        for insert_index in indices_to_insert:
          if insert_index < index:
            adjusted_index += 1
        adjusted_delete_indices.append(adjusted_index)

    modified_array = np.delete(modified_array, adjusted_delete_indices)

    return modified_array


original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result_array = modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete)
result_array


array([ 1, 10,  3,  4,  5])

In [55]:
# Q51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
# Perform element-wise addition between `arr1` and `arr2`.

# Ans.

# Create arr1 with random integers (adjust size as needed)
arr1 = np.random.randint(0, 100, size=10)  # Example: 10 random integers between 0 and 99

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)  # Integers from 1 to 10 (inclusive)


# Ensure both arrays have compatible shapes for element-wise addition
if arr1.shape != arr2.shape:
    # Handle shape mismatch (e.g., broadcasting, resizing, or error handling)
    min_len = min(arr1.shape[0], arr2.shape[0])
    arr1 = arr1[:min_len]
    arr2 = arr2[:min_len]

# Perform element-wise addition
element_wise_sum = arr1 + arr2
element_wise_sum


array([ 5, 19, 94, 20, 90, 95, 84, 75, 21, 44])

In [56]:
# Q52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
# from 1 to 10. Subtract `arr2` from `arr1` element-wise.

# Ans.

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)

result_array = arr1 - arr2
result_array


array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

In [57]:
# Q53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
# Perform element-wise multiplication between `arr1` and `arr2`.


# Ans.

# Create arr1 with random integers
arr1 = np.random.randint(0, 10, size=5)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise multiplication
element_wise_product = arr1 * arr2

element_wise_product


array([ 0,  6, 15,  0, 30])

In [58]:
# Q54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
# to 5. Perform element-wise division of `arr1` by `arr2`.

# Ans.

arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)

result = arr1 / arr2
result


array([2., 2., 2., 2., 2.])

In [59]:
# Q55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
# reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

# Ans.

arr1 = np.arange(1, 6)
arr2 = np.arange(5, 0, -1)

result_array = np.power(arr1, arr2)
result_array


array([ 1, 16, 27, 16,  5])

In [60]:
# Q56.  Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
#  arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# Ans.

def count_substring_occurrences(arr, substring):
    """
    Counts the occurrences of a specific substring within a NumPy array of strings.

    Args:
        arr (np.ndarray): A NumPy array of strings.
        substring (str): The substring to search for.

    Returns:
        int: The number of times the substring appears in the array.
    """
    count = 0
    for string in arr:
        count += string.count(substring)
    return count

# Example usage:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
occurrences = count_substring_occurrences(arr, substring)
print(f"The substring '{substring}' appears {occurrences} times in the array.")


The substring 'hello' appears 3 times in the array.


In [61]:
# Q57. Write a function that extracts uppercase characters from a NumPy array of strings.
#  arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
#  arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Ans.

def extract_uppercase(arr):
    """
    Extracts uppercase characters from a NumPy array of strings.

    Args:
        arr: A NumPy array of strings.

    Returns:
        A NumPy array containing only the uppercase characters from the input array.
    """
    uppercase_chars = []
    for string in arr:
        for char in string:
            if 'A' <= char <= 'Z':
                uppercase_chars.append(char)
    return np.array(uppercase_chars)

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_array = extract_uppercase(arr)
uppercase_array


array(['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T'], dtype='<U1')

In [62]:
# Q58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
#  arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Ans.

def replace_substring(arr, old, new):
    """
    Replaces occurrences of a substring in a NumPy array of strings.

    Args:
        arr (np.ndarray): The input array of strings.
        old (str): The substring to be replaced.
        new (str): The new substring.

    Returns:
        np.ndarray: A new array with the substrings replaced.
    """
    new_arr = np.array([string.replace(old, new) for string in arr])
    return new_arr

# Example
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
new_arr = replace_substring(arr, 'apple', 'orange')
new_arr


array(['orange', 'banana', 'grape', 'pineorange'], dtype='<U10')

In [64]:
# Q59. Write a function that concatenates strings in a NumPy array element-wise.
#  arr1 = np.array(['Hello', 'World'])
#  arr2 = np.array(['Open', 'AI'])

# Ans.

def concatenate_strings(arr1, arr2):
    """
    Concatenates strings in two NumPy arrays element-wise.

    Args:
        arr1: The first NumPy array of strings.
        arr2: The second NumPy array of strings.

    Returns:
        A new NumPy array with the concatenated strings, or None if the input is invalid.
    """
    if not isinstance(arr1, np.ndarray) or not isinstance(arr2, np.ndarray):
        print("Error: Inputs must be NumPy arrays.")
        return None

    if arr1.shape != arr2.shape:
        print("Error: Input arrays must have the same shape.")
        return None

    if arr1.dtype != 'U' or arr2.dtype != 'U':
        print("Error: Input arrays must contain strings.")
        return None

    return np.char.add(arr1, arr2)

# Example usage
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
result_array = concatenate_strings(arr1, arr2)
result_array


Error: Input arrays must contain strings.


In [65]:
# Q60. Write a function that finds the length of the longest string in a NumPy array.
#  arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
#  arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Ans.

def longest_string_length(arr):
    """
    Finds the length of the longest string in a NumPy array.

    Args:
        arr (np.ndarray): A NumPy array of strings.

    Returns:
        int: The length of the longest string in the array.
             Returns 0 if the array is empty or contains non-string elements.
    """
    if not isinstance(arr, np.ndarray):
        print("Error: Input must be a NumPy array.")
        return 0

    if arr.size == 0:
        return 0

    max_length = 0
    for item in arr:
        if isinstance(item, str):
            max_length = max(max_length, len(item))
        else:
            print("Warning: Non-string element found in the array. Skipping.")

    return max_length

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
length = longest_string_length(arr)
print(f"The length of the longest string is: {length}")


The length of the longest string is: 9


In [66]:
# Q61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
# standard deviation of the dataset using NumPy's functions.

# Ans.

# Create a dataset of 100 random integers between 1 and 1000
data = np.random.randint(1, 1001, size=100)

# Compute the mean
mean = np.mean(data)
print(f"Mean: {mean}")

# Compute the median
median = np.median(data)
print(f"Median: {median}")

# Compute the variance
variance = np.var(data)
print(f"Variance: {variance}")

# Compute the standard deviation
std_dev = np.std(data)
print(f"Standard Deviation: {std_dev}")


Mean: 503.31
Median: 516.5
Variance: 89148.47389999998
Standard Deviation: 298.5774169290102


In [67]:
# Q62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
# dataset.

# Ans.

# Generate an array of 50 random numbers between 1 and 100
random_numbers = np.random.randint(1, 101, size=50)

# Find the 25th percentile
percentile_25 = np.percentile(random_numbers, 25)
print(f"25th percentile: {percentile_25}")

# Find the 75th percentile
percentile_75 = np.percentile(random_numbers, 75)
print(f"75th percentile: {percentile_75}")


25th percentile: 23.0
75th percentile: 73.5


In [68]:
# Q63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
# arrays using NumPy's `corrcoef` function.


# Ans.

def compute_correlation(arr1, arr2):
    """
    Computes the correlation coefficient between two arrays.

    Args:
        arr1: The first array.
        arr2: The second array.

    Returns:
        The correlation coefficient between the two arrays.
        Returns None if the arrays have incompatible shapes or are not 1D.
    """
    if not isinstance(arr1, np.ndarray) or not isinstance(arr2, np.ndarray):
      print("Error: Inputs must be NumPy arrays.")
      return None
    if arr1.ndim != 1 or arr2.ndim !=1:
      print("Error: Input arrays must be 1D.")
      return None
    if arr1.shape != arr2.shape:
      print("Error: Input arrays must have the same shape.")
      return None

    correlation_matrix = np.corrcoef(arr1, arr2)
    return correlation_matrix[0, 1]

# Example usage
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

correlation_coefficient = compute_correlation(arr1, arr2)

if correlation_coefficient is not None:
    print(f"Correlation Coefficient: {correlation_coefficient}")


Correlation Coefficient: -0.9999999999999999


In [69]:
# Q64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

# Ans.

def matrix_multiplication(matrix1, matrix2):
    """
    Performs matrix multiplication using NumPy's dot function.

    Args:
        matrix1: The first matrix (NumPy array).
        matrix2: The second matrix (NumPy array).

    Returns:
        The resulting matrix from the multiplication, or None if the matrices are incompatible.
    """
    try:
        result_matrix = np.dot(matrix1, matrix2)
        return result_matrix
    except ValueError as e:
        print(f"Error: {e}")
        return None

# Example usage
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

product_matrix = matrix_multiplication(matrix_a, matrix_b)

if product_matrix is not None:
  product_matrix


In [70]:
# Q65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
# percentiles along with the first and third quartiles.

# Ans.

# Create an array of 50 integers between 10 and 1000
data = np.random.randint(10, 1001, size=50)

# Calculate percentiles and quartiles
tenth_percentile = np.percentile(data, 10)
fiftieth_percentile = np.percentile(data, 50)  # Median
ninetieth_percentile = np.percentile(data, 90)
first_quartile = np.percentile(data, 25)
third_quartile = np.percentile(data, 75)

print("10th Percentile:", tenth_percentile)
print("50th Percentile (Median):", fiftieth_percentile)
print("90th Percentile:", ninetieth_percentile)
print("First Quartile (25th Percentile):", first_quartile)
print("Third Quartile (75th Percentile):", third_quartile)


10th Percentile: 108.5
50th Percentile (Median): 557.5
90th Percentile: 883.5
First Quartile (25th Percentile): 250.0
Third Quartile (75th Percentile): 763.5


In [71]:
# Q66. Create a NumPy array of integers and find the index of a specific element.

# Ans.

# Create a NumPy array of integers
my_array = np.array([10, 25, 5, 40, 15, 30])

# Find the index of a specific element (e.g., 40)
element_to_find = 40
index = np.where(my_array == element_to_find)

# Print the index
print(f"The index of {element_to_find} is: {index[0][0]}")


The index of 40 is: 3


In [72]:
# Q67. Generate a random NumPy array and sort it in ascending order.

# Ans.

# Generate a random NumPy array
random_array = np.random.rand(10)  # Example: array of 10 random numbers

# Sort the array in ascending order
sorted_array = np.sort(random_array)

print("Original array:", random_array)
print("Sorted array:", sorted_array)


Original array: [0.57363822 0.8082009  0.17305727 0.92816135 0.81956714 0.73082209
 0.30048476 0.248377   0.05770313 0.31950221]
Sorted array: [0.05770313 0.17305727 0.248377   0.30048476 0.31950221 0.57363822
 0.73082209 0.8082009  0.81956714 0.92816135]


In [73]:
# Q68. Filter elements >20  in the given NumPy array.
#  arr = np.array([12, 25, 6, 42, 8, 30])

# Ans.
arr = np.array([12, 25, 6, 42, 8, 30])
filtered_arr = arr[arr > 20]
filtered_arr


array([25, 42, 30])

In [74]:
# Q69. Filter elements which are divisible by 3 from a given NumPy array.
#  arr = np.array([1, 5, 8, 12, 15])

# Ans.

arr = np.array([1, 5, 8, 12, 15])
filtered_arr = arr[arr % 3 == 0]
filtered_arr


array([12, 15])

In [75]:
# Q70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
#  arr = np.array([10, 20, 30, 40, 50])

# Ans.

arr = np.array([10, 20, 30, 40, 50])
filtered_arr = arr[(arr >= 20) & (arr <= 40)]
filtered_arr


array([20, 30, 40])

In [76]:
# Q71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
#  arr = np.array([1, 2, 3])

# Ans.

arr = np.array([1, 2, 3])
arr.dtype.byteorder


'='

In [77]:
# Q72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
#  arr = np.array([1, 2, 3], dtype=np.int32)

# Ans.
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
arr


array([16777216, 33554432, 50331648], dtype=int32)

In [78]:
# Q73. For the given NumPy array, swap its byte order without modifying the original array using
# `newbyteorder()`.
#  arr = np.array([1, 2, 3], dtype=np.int32)

# Ans.

arr = np.array([1, 2, 3], dtype=np.int32)
new_arr = arr.newbyteorder()
new_arr


array([16777216, 33554432, 50331648], dtype='>i4')

In [79]:
# Q74. For the given NumPy array and swap its byte order conditionally based on system endianness using
# `newbyteorder()`.
#  arr = np.array([1, 2, 3], dtype=np.int32)

# Ans.

arr = np.array([1, 2, 3], dtype=np.int32)
new_arr = arr.newbyteorder('<' if arr.dtype.byteorder == '>' else '>')
new_arr


array([16777216, 33554432, 50331648], dtype='>i4')

In [80]:
# Q75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
# attribute `byteorder`.
#  arr = np.array([1, 2, 3], dtype=np.int32)

# Ans.

arr = np.array([1, 2, 3], dtype=np.int32)
arr.dtype.byteorder


'='

In [81]:
# Q76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
# an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

# Ans.

# Create arr1 with values from 1 to 10
arr1 = np.arange(1, 11)

# Create a copy of arr1
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 99

# Check if arr1 is affected
print("Original array:", arr1)
print("Copied array:", copy_arr)


Original array: [ 1  2  3  4  5  6  7  8  9 10]
Copied array: [99  2  3  4  5  6  7  8  9 10]


In [82]:
# Q77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

# Ans.

# Create a 2D NumPy array with random integers
matrix = np.random.randint(0, 10, size=(3, 3))

# Extract a slice (view) from the matrix
view_slice = matrix[0:2, 0:2]  # Example slice

# Modify an element in the slice
view_slice[0, 0] = 99

# Check if the original matrix is modified
print("Original matrix:\n", matrix)
print("\nModified slice:\n", view_slice)


Original matrix:
 [[99  5  3]
 [ 0  9  9]
 [ 0  0  4]]

Modified slice:
 [[99  5]
 [ 0  9]]


In [83]:
# Q78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

# Ans.

# Create array_a
array_a = np.arange(1, 13).reshape(4, 3)

# Extract a slice (view)
view_b = array_a[0:2, 0:2]

# Broadcast addition of 5 to the slice
view_b += 5

# Check if the original array is modified
print("Original array_a:\n", array_a)


Original array_a:
 [[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]


In [84]:
# Q79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
# `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
# reflects changes in the original `orig_array`.

# Ans.

# Create the original array
orig_array = np.arange(1, 9).reshape(2, 4)

# Create a reshaped view
reshaped_view = orig_array.reshape(4, 2)

# Modify an element in the reshaped view
reshaped_view[0, 0] = 99

# Check if the change is reflected in the original array
print("Original array:\n", orig_array)
print("\nReshaped view:\n", reshaped_view)


Original array:
 [[99  2  3  4]
 [ 5  6  7  8]]

Reshaped view:
 [[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


In [85]:
# Q80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

# Ans.

# Create a NumPy array with random integers
data = np.random.randint(0, 10, size=(3, 4))

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Modify an element in data_copy
data_copy[0] = 99

# Verify if the original data is affected
print("Original data:\n", data)
print("\nModified data_copy:\n", data_copy)


Original data:
 [[7 3 4 5]
 [3 5 8 6]
 [9 0 8 4]]

Modified data_copy:
 [99  8  6  9  8]


In [86]:
# Q81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
# operations between them.

# Ans.

# Create two matrices A and B of identical shape
shape = (3, 3)  # Example shape, you can change this
A = np.random.randint(0, 10, size=shape)
B = np.random.randint(0, 10, size=shape)

# Perform addition
addition_result = A + B
print("Addition Result:\n", addition_result)

# Perform subtraction
subtraction_result = A - B
print("Subtraction Result:\n", subtraction_result)


Addition Result:
 [[10  9 11]
 [ 9 16 11]
 [10 11 12]]
Subtraction Result:
 [[ 4  5 -1]
 [-3 -2 -3]
 [-8  3  4]]


In [87]:
# Q82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

# Ans.

# Generate matrix C (3x2)
C = np.random.randint(0, 10, size=(3, 2))

# Generate matrix D (2x4)
D = np.random.randint(0, 10, size=(2, 4))

# Perform matrix multiplication
result_matrix = np.dot(C, D)

# Print the result
print("Matrix C:\n", C)
print("\nMatrix D:\n", D)
print("\nResultant Matrix (C x D):\n", result_matrix)


Matrix C:
 [[4 9]
 [9 1]
 [2 2]]

Matrix D:
 [[0 3 6 5]
 [3 8 8 6]]

Resultant Matrix (C x D):
 [[27 84 96 74]
 [ 3 35 62 51]
 [ 6 22 28 22]]


In [88]:
# Q83. Create a matrix `E` and find its transpose.

# Ans.

# Create matrix E (example 3x2 matrix)
E = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Find the transpose of matrix E
E_transpose = np.transpose(E)

# Print the original and transposed matrices
print("Original Matrix E:\n", E)
print("\nTranspose of Matrix E:\n", E_transpose)


Original Matrix E:
 [[1 2]
 [3 4]
 [5 6]]

Transpose of Matrix E:
 [[1 3 5]
 [2 4 6]]


In [89]:
# Q84. Generate a square matrix `F` and compute its determinant.

# Ans.

# Create a square matrix F (example 3x3 matrix)
F = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute the determinant of matrix F
determinant_F = np.linalg.det(F)

# Print the determinant
print("Matrix F:\n", F)
print("\nDeterminant of Matrix F:", determinant_F)


Matrix F:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of Matrix F: 0.0


In [90]:
# Q85. Create a square matrix `G` and find its inverse.

# Ans.
# Create a square matrix G
G = np.array([[1, 2],
              [3, 4]])

# Compute the inverse of matrix G
G_inverse = np.linalg.inv(G)

# Print the original and inverse matrices
print("Original Matrix G:\n", G)
print("\nInverse of Matrix G:\n", G_inverse)


Original Matrix G:
 [[1 2]
 [3 4]]

Inverse of Matrix G:
 [[-2.   1. ]
 [ 1.5 -0.5]]
